#this line is not needed since Docker-compose v2.x
#version: '3.8'

#i used the idea of the base from OtheloPlusPlus 
services:
  base:
    container_name: inception
    image: inception:base
    build:
      context: ./requirements/base
      dockerfile: Dockerfile
    restart: "no"

  nginx:
    container_name: nginx 
    volumes:
    - wordpress:/var/www/html
    networks:
    - inception
    depends_on: #start nginx after base and wordpress
      - base
      - wordpress
    build: requirements/nginx
    env_file: .env
    ports:
    - "8443:8443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/html
    networks:
    - inception
    build: requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    expose: 
    - "9000"

  mariadb:
    build: requirements/mariadb
    env_file: .env
    container_name: mariadb_container
    depends_on:
      - base
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    networks:
      - inception

volumes:
  wordpress:
    driver: local 
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${HOME}/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: ${HOME}/data/mariadb

networks:
  inception:
    driver: bridge #explain to docker to install automatically rules for containers to communicate

