#this line is not needed since Docker-compose v2.x
#version: '3.8'

#i used the idea of the base from OtheloPlusPlus 
services:
  base:
    container_name: inception
    image: inception:base
    build:
      context: ./requirements/base
      dockerfile: Dockerfile
    restart: "no"

  nginx:
    container_name: nginx 
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    depends_on:        			 # Nouvelle ligne, indiquant de ne pas démarrer NGINX tant que WordPress n'a pas démarré.
      - base
      - wordpress
    build: requirements/nginx
    env_file: .env
    ports:
    - "443:443" 		# on indique le port qui sera exposé a la machine locale
    restart: on-failure

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    build: requirements/wordpress
    depends_on:   					# WordPress démarrera uniquement après MariaDB (sinon il ne pourra pas configurer la base de données...)
      - base
      - mariadb
    restart: on-failure
    expose: 
    - "9000"

  mariadb:
    build: requirements/mariadb
    env_file: .env
    container_name: mariadb_container
    depends_on:
      - base
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    networks:
      - inception

volumes:
  wordpress:
    driver: local # ici nous stockons le volume en local
    driver_opts:
      type: 'none' 									# aucun type spécifique
      o: 'bind'
      device: ${HOME}/data/wordpress 		#Ou stocker le dossier sur votre ordinateur en local
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'										 # Les Bind Mounts sont des volumes qui se montent sur un chemin d'accès à l'hôte, et ils peuvent être modifiés par d'autres processus en dehors de docker.
      device: ${HOME}/data/mariadb			#Ou stocker le dossier sur votre ordinateur en local

networks:
  inception:
    driver: bridge #explain to docker to install automatically rules for containers to communicate

