# Dockerfile for MariaDB

FROM mariadb:latest

# Environment variables for MariaDB
# ENV MYSQL_ROOT_PASSWORD=root_password
# ENV MYSQL_DATABASE=my_database
# ENV MYSQL_USER=my_user
# ENV MYSQL_PASSWORD=my_password

# Copy custom configuration files, if any
# COPY ./path/to/custom/config.cnf /etc/mysql/conf.d/

# Expose port 3306 for MariaDB
EXPOSE 3306

# Run the MariaDB server
# CMD ["mysqld"]